/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.StringTokenizer;

/**
 *
 * @author alex
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    fsarraylist estudiantes = new fsarraylist(20);
    fsarraylist estudiantes_notas = new fsarraylist(20);
    int random;
    int position=0;
    public NewJFrame() {
        initComponents();
        this.setLocationRelativeTo(this);
        try{
        String s1;
        String s2;
        String nombre="";
        int cuenta=0;
        String carrera="";
        int con=1,pos=0;
        
        BufferedReader br = new BufferedReader (new FileReader("estudiantes.txt"));
      
        s1 = br.readLine();
 
        int numTokens = 0;
        StringTokenizer st = new StringTokenizer(s1);

        
        while (st.hasMoreTokens())
        {
            s2 = st.nextToken();
            numTokens++;
            if (con==4 ) {
                estudiantes.insert(new estudiante(nombre, cuenta, carrera), pos);
                pos++;
                con=1;
            }
            if(con==1){
                nombre=s2;
                con++;
            }else if(con==2){
                cuenta = Integer.parseInt(s2);
                con++;
            }else if(con==3){
                carrera=s2;
                con++;
            }
        }
        estudiantes.insert(new estudiante(nombre, cuenta, carrera), pos);
        
        br.close();
        }catch (Exception e){ //Catch de excepciones
            System.err.println("Ocurrio un error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asig_nota = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        nombre_e = new javax.swing.JLabel();
        nota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        listo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        asignar_nota = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        jLabel1.setText("Estudiante:");

        nombre_e.setText("------------------------------------------");

        jLabel3.setText("asigne su nota:");

        listo.setText("Listo");
        listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoActionPerformed(evt);
            }
        });

        jButton1.setText("cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout asig_notaLayout = new javax.swing.GroupLayout(asig_nota.getContentPane());
        asig_nota.getContentPane().setLayout(asig_notaLayout);
        asig_notaLayout.setHorizontalGroup(
            asig_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asig_notaLayout.createSequentialGroup()
                .addGroup(asig_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(asig_notaLayout.createSequentialGroup()
                        .addGroup(asig_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(asig_notaLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(asig_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addGroup(asig_notaLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nombre_e, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nota)))
                            .addGroup(asig_notaLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(listo)))
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asig_notaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        asig_notaLayout.setVerticalGroup(
            asig_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asig_notaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(17, 17, 17)
                .addGroup(asig_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre_e))
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(listo)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("Proyecto 1");
        titulo.setToolTipText("");

        asignar_nota.setText("Asignar una nota");
        asignar_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignar_notaActionPerformed(evt);
            }
        });

        salir.setText("guardar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(asignar_nota, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(asignar_nota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asignar_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignar_notaActionPerformed
        // TODO add your handling code here:
        random=(int)(Math.random()*(estudiantes.size) + 0);
        nombre_e.setText(estudiantes.get(random).toString());
        this.setVisible(false);
        asig_nota.setSize(500,400);
        asig_nota.setLocationRelativeTo(this);
        asig_nota.setVisible(true);
    }//GEN-LAST:event_asignar_notaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        asig_nota.setVisible(false);
        this.setVisible(true);
        nota.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoActionPerformed
        // TODO add your handling code here:
        boolean salir = false;
        int crear = 0;
        if ( estudiantes_notas.size()!=0) {
           for (int i = 0; i < estudiantes_notas.size(); i++) {
                if (((estudiante)estudiantes.get(random)).getNum_cuenta()==((estudiantes_notas)estudiantes_notas.get(i)).getNum_cuenta()) {
                    crear=2;
                }
            } 
        }else{
            estudiantes_notas.insert(new estudiantes_notas(((estudiante)estudiantes.get(random)).getNum_cuenta()),position);
            position++;  
            crear=2;
        }
        if (crear!=2) {
            estudiantes_notas.insert(new estudiantes_notas(((estudiante)estudiantes.get(random)).getNum_cuenta()),position);
            position++;  
        }
        if(Integer.parseInt(nota.getText())>100 || Integer.parseInt(nota.getText())<0){
            nota.setText("");
        }else{
            salir=true;
        }
        if (salir==true) {
            for (int i = 0; i < estudiantes_notas.size(); i++) {
                if (((estudiantes_notas)estudiantes_notas.get(i)).getNum_cuenta()==((estudiante)estudiantes.get(random)).getNum_cuenta()) {
                    ((estudiantes_notas)estudiantes_notas.get(i)).agregar_nota(Integer.parseInt(nota.getText()));
                }
            }
            nota.setText("");
            asig_nota.setVisible(false);
            this.setVisible(true);
            crear=0;
        }
    }//GEN-LAST:event_listoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        try {
            PrintWriter pw = new PrintWriter(new File("notas.csv"));
            StringBuilder sb = new StringBuilder();
            sb.append("id");
            sb.append(',');
            sb.append("Nota");
            sb.append('\n');

            for (int i = 0; i < estudiantes_notas.size(); i++) {
                sb.append(((estudiantes_notas)estudiantes_notas.get(i)).getNum_cuenta());
                sb.append(',');
                sb.append(((estudiantes_notas)estudiantes_notas.get(i)).promedio());
                sb.append('\n');   
            }
            pw.write(sb.toString());
            pw.close();
            System.out.println("guardado!");  
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog asig_nota;
    private javax.swing.JButton asignar_nota;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton listo;
    private javax.swing.JLabel nombre_e;
    private javax.swing.JTextField nota;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
